package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentSearchHistory;
import com.csmaxwell.srent.db.domain.SrentSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    long countByExample(SrentSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(SrentSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int insert(SrentSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int insertSelective(SrentSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    SrentSearchHistory selectOneByExample(SrentSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    SrentSearchHistory selectOneByExampleSelective(@Param("example") SrentSearchHistoryExample example, @Param("selective") SrentSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    List<SrentSearchHistory> selectByExampleSelective(@Param("example") SrentSearchHistoryExample example, @Param("selective") SrentSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    List<SrentSearchHistory> selectByExample(SrentSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    SrentSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    SrentSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    SrentSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentSearchHistory record, @Param("example") SrentSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentSearchHistory record, @Param("example") SrentSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}