package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentLog;
import com.csmaxwell.srent.db.domain.SrentLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    long countByExample(SrentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int deleteByExample(SrentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int insert(SrentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int insertSelective(SrentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    SrentLog selectOneByExample(SrentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    SrentLog selectOneByExampleSelective(@Param("example") SrentLogExample example, @Param("selective") SrentLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    List<SrentLog> selectByExampleSelective(@Param("example") SrentLogExample example, @Param("selective") SrentLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    List<SrentLog> selectByExample(SrentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    SrentLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    SrentLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    SrentLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentLog record, @Param("example") SrentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentLog record, @Param("example") SrentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}