package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentCategory;
import com.csmaxwell.srent.db.domain.SrentCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    long countByExample(SrentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int deleteByExample(SrentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int insert(SrentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int insertSelective(SrentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    SrentCategory selectOneByExample(SrentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    SrentCategory selectOneByExampleSelective(@Param("example") SrentCategoryExample example, @Param("selective") SrentCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    List<SrentCategory> selectByExampleSelective(@Param("example") SrentCategoryExample example, @Param("selective") SrentCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    List<SrentCategory> selectByExample(SrentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    SrentCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    SrentCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    SrentCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentCategory record, @Param("example") SrentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentCategory record, @Param("example") SrentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}