package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentOrderGoods;
import com.csmaxwell.srent.db.domain.SrentOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    long countByExample(SrentOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(SrentOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int insert(SrentOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(SrentOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    SrentOrderGoods selectOneByExample(SrentOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    SrentOrderGoods selectOneByExampleSelective(@Param("example") SrentOrderGoodsExample example, @Param("selective") SrentOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    List<SrentOrderGoods> selectByExampleSelective(@Param("example") SrentOrderGoodsExample example, @Param("selective") SrentOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    List<SrentOrderGoods> selectByExample(SrentOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    SrentOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    SrentOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    SrentOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentOrderGoods record, @Param("example") SrentOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentOrderGoods record, @Param("example") SrentOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}