package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentRole;
import com.csmaxwell.srent.db.domain.SrentRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    long countByExample(SrentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int deleteByExample(SrentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int insert(SrentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int insertSelective(SrentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    SrentRole selectOneByExample(SrentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    SrentRole selectOneByExampleSelective(@Param("example") SrentRoleExample example, @Param("selective") SrentRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    List<SrentRole> selectByExampleSelective(@Param("example") SrentRoleExample example, @Param("selective") SrentRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    List<SrentRole> selectByExample(SrentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    SrentRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    SrentRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    SrentRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentRole record, @Param("example") SrentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentRole record, @Param("example") SrentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}