package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentKeyword;
import com.csmaxwell.srent.db.domain.SrentKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    long countByExample(SrentKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(SrentKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int insert(SrentKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int insertSelective(SrentKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    SrentKeyword selectOneByExample(SrentKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    SrentKeyword selectOneByExampleSelective(@Param("example") SrentKeywordExample example, @Param("selective") SrentKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    List<SrentKeyword> selectByExampleSelective(@Param("example") SrentKeywordExample example, @Param("selective") SrentKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    List<SrentKeyword> selectByExample(SrentKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    SrentKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    SrentKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    SrentKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentKeyword record, @Param("example") SrentKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentKeyword record, @Param("example") SrentKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}