package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentTopic;
import com.csmaxwell.srent.db.domain.SrentTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    long countByExample(SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int deleteByExample(SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int insert(SrentTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int insertSelective(SrentTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    SrentTopic selectOneByExample(SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    SrentTopic selectOneByExampleSelective(@Param("example") SrentTopicExample example, @Param("selective") SrentTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    SrentTopic selectOneByExampleWithBLOBs(SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    List<SrentTopic> selectByExampleSelective(@Param("example") SrentTopicExample example, @Param("selective") SrentTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    List<SrentTopic> selectByExampleWithBLOBs(SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    List<SrentTopic> selectByExample(SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    SrentTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    SrentTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    SrentTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentTopic record, @Param("example") SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") SrentTopic record, @Param("example") SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentTopic record, @Param("example") SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SrentTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}