package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentUser;
import com.csmaxwell.srent.db.domain.SrentUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    long countByExample(SrentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int deleteByExample(SrentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int insert(SrentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int insertSelective(SrentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    SrentUser selectOneByExample(SrentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    SrentUser selectOneByExampleSelective(@Param("example") SrentUserExample example, @Param("selective") SrentUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    List<SrentUser> selectByExampleSelective(@Param("example") SrentUserExample example, @Param("selective") SrentUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    List<SrentUser> selectByExample(SrentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    SrentUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    SrentUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    SrentUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentUser record, @Param("example") SrentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentUser record, @Param("example") SrentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}