package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentAdmin;
import com.csmaxwell.srent.db.domain.SrentAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    long countByExample(SrentAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int deleteByExample(SrentAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int insert(SrentAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int insertSelective(SrentAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    SrentAdmin selectOneByExample(SrentAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    SrentAdmin selectOneByExampleSelective(@Param("example") SrentAdminExample example, @Param("selective") SrentAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    List<SrentAdmin> selectByExampleSelective(@Param("example") SrentAdminExample example, @Param("selective") SrentAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    List<SrentAdmin> selectByExample(SrentAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    SrentAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    SrentAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    SrentAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentAdmin record, @Param("example") SrentAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentAdmin record, @Param("example") SrentAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}