package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentSystem;
import com.csmaxwell.srent.db.domain.SrentSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    long countByExample(SrentSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int deleteByExample(SrentSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int insert(SrentSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int insertSelective(SrentSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    SrentSystem selectOneByExample(SrentSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    SrentSystem selectOneByExampleSelective(@Param("example") SrentSystemExample example, @Param("selective") SrentSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    List<SrentSystem> selectByExampleSelective(@Param("example") SrentSystemExample example, @Param("selective") SrentSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    List<SrentSystem> selectByExample(SrentSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    SrentSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    SrentSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    SrentSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentSystem record, @Param("example") SrentSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentSystem record, @Param("example") SrentSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}