package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentStorage;
import com.csmaxwell.srent.db.domain.SrentStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    long countByExample(SrentStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int deleteByExample(SrentStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int insert(SrentStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int insertSelective(SrentStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    SrentStorage selectOneByExample(SrentStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    SrentStorage selectOneByExampleSelective(@Param("example") SrentStorageExample example, @Param("selective") SrentStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    List<SrentStorage> selectByExampleSelective(@Param("example") SrentStorageExample example, @Param("selective") SrentStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    List<SrentStorage> selectByExample(SrentStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    SrentStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    SrentStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    SrentStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentStorage record, @Param("example") SrentStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentStorage record, @Param("example") SrentStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}