package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentUserFormid;
import com.csmaxwell.srent.db.domain.SrentUserFormidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    long countByExample(SrentUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(SrentUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int insert(SrentUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(SrentUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    SrentUserFormid selectOneByExample(SrentUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    SrentUserFormid selectOneByExampleSelective(@Param("example") SrentUserFormidExample example, @Param("selective") SrentUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    List<SrentUserFormid> selectByExampleSelective(@Param("example") SrentUserFormidExample example, @Param("selective") SrentUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    List<SrentUserFormid> selectByExample(SrentUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    SrentUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    SrentUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    SrentUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentUserFormid record, @Param("example") SrentUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentUserFormid record, @Param("example") SrentUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}