package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentOrder;
import com.csmaxwell.srent.db.domain.SrentOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    long countByExample(SrentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int deleteByExample(SrentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int insert(SrentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int insertSelective(SrentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    SrentOrder selectOneByExample(SrentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    SrentOrder selectOneByExampleSelective(@Param("example") SrentOrderExample example, @Param("selective") SrentOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    List<SrentOrder> selectByExampleSelective(@Param("example") SrentOrderExample example, @Param("selective") SrentOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    List<SrentOrder> selectByExample(SrentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    SrentOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    SrentOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    SrentOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentOrder record, @Param("example") SrentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentOrder record, @Param("example") SrentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}