package com.csmaxwell.srent.db.dao;

import com.csmaxwell.srent.db.domain.SrentRegion;
import com.csmaxwell.srent.db.domain.SrentRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrentRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    long countByExample(SrentRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int deleteByExample(SrentRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int insert(SrentRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int insertSelective(SrentRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    SrentRegion selectOneByExample(SrentRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    SrentRegion selectOneByExampleSelective(@Param("example") SrentRegionExample example, @Param("selective") SrentRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    List<SrentRegion> selectByExampleSelective(@Param("example") SrentRegionExample example, @Param("selective") SrentRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    List<SrentRegion> selectByExample(SrentRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    SrentRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SrentRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    SrentRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    SrentRegion selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrentRegion record, @Param("example") SrentRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrentRegion record, @Param("example") SrentRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrentRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrentRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SrentRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srent_region
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}